// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    InfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MPIcon: typeof import('./src/components/MPIcon.vue')['default']
    MPOptIcon: typeof import('./src/components/MPOptIcon.vue')['default']
    MpOptSpecialIcon: typeof import('./src/components/MpOptSpecialIcon.vue')['default']
    MPSearch: typeof import('./src/components/MPSearch.vue')['default']
    MPVideoCard: typeof import('./src/components/MPVideoCard.vue')['default']
    MPVideoPlayer: typeof import('./src/components/MPVideoPlayer.vue')['default']
  }
}

export { }
